const output = [
  "community powered by blockchain technologies to your inbox partners",
  "the tool for trainers and addresses to help them with mentors",
  "the best way to monetize your chat",
  "stop wasting time recreating bugs on - the - go .",
  "ai powered website builder",
  '" a new way to create , manage and share your content on your web - site "',
  "gather actionable feedback from anywhere in europe",
  '" get feedback from around you , subscribe to the world "',
  '" save , organize and share your favorite pieces of your favorite over "',
  "save money on the go you",
  "schedule and share your next idea",
  "create your own website from group benefits",
  "boost your team ' s data into spreadsheet",
  '" discover , connect and engage with the internet , and offline travel "',
  "design and tools for user experience",
  "improve your drawing skills always up with a beautiful dashboard",
  "speak with your friends and get a swipe every day",
  "filter the roi of your enterprise",
  "customized tailor - made jeans delivered to your door",
  "a place where you can trust to do github",
  "a social network for high school industry",
  "resource management tool for developers",
  "power up your email crm",
  "create and share your personal website using different things",
  "a simple and easy way to create your content",
  "a new way to experience your day",
  "saving & analyze any html and get notified in your smartphone",
  "play with your gallery instead of fighting it from transcribed",
  "social media marketing platform",
  "the smart way to share your day",
  "laundry for your transactional favorite tab",
  "a social network for translating people",
  "online appointment scheduling webapp",
  '" a new way to discover , connect and communicate with your job "',
  "meet people with friends who know in your friends",
  "customized tailor - made jeans delivered to your document",
  "create your own hackernews map with a single tap",
  "turn your website traffic into a live video .",
  "get a t - shirt with your favorite restaurants",
  "connecting the worlds greatest music in the world",
  "ready to use modals between coffeeshops and travelers",
  "look and discovering music in your child",
  "new way to create a status page for your instagram",
  "a new way to discover and share events in the world",
  "discover and share whats authentic notes",
  "a better way to keep track of contacts on your goals",
  "use your phone number through an adventure",
  "performance monitoring for react product",
  "starting the journey to empower your calls",
  "fast and easy way to share your mobile apps with no - code",
  "your personal assistant to read it ' s more",
  "curated list of information by founders and their favorite destinations",
  "tell the world of hidden relevant links",
  "be the news anchor",
  "analytics for your transactional emails",
  "dating app for rideshare drivers",
  "get your ebooks into a subscription team",
  "open source platform to website is a service experience",
  "easily connect with the right people around you .",
  "manage your pantry inventory wisely .",
  "a free online vr marketplace",
  "changing the way of creating a connection at the best music",
  '" a simple , interactive way to learn & events with friends for . "',
  '" a new way to create , manage and share your content shows "',
  "a better way to manage your projects",
  '" the easiest way to discover , onboard & events around you "',
  "trade your unwanted items around you",
  "# 1 forex trading for small businesses",
  "collect your mobile app with one line of code",
  "build a beautiful website - in - 1 with ease",
  "tells you when you are in a swipe or",
  '" a new way to discover , connect and communicate with your cryptocurrency portfolio "',
  "advice for professionals",
  "business insight through your website visitors",
  "practice management made easy",
  "social media marketing platform that helps businesses to realise their learning content",
  "keep track of your dog ' s latest work",
  "crypto price protection",
  "dropshipping marketplace for startups and small businesses",
  '" get feedback from any website , subscribe to your own online "',
  "best profitability accounting software",
  "flexible workspaces for stripe",
  "easiest way to kickoff built for your business applications",
  "get your ducks in style",
  "fix - free online salesforce quotes for ios .",
  "turn your website visitors into a beautiful website users",
  '" easily manage your data , heirs , nps , and more fun "',
  "a new way to make meetings and distribute your video content",
  '" create , deploy , and share stories from any app "',
  "the first app that makes it to the right person to a better way you",
  "omnichannel retail platform",
  "automatic and human website for your phone",
  "manage your crypto portfolio with ease",
  "make & share predictions and videos",
  "show all your social activity and connect with the right motivation",
  "one link to manage your team",
  "google analytics for your shopify",
  "a social network for passionate people",
  "save your website for every webshop",
  '" track , manage and monitor your links and sales and marketing group "',
  '" a new way to discover , save and share content on your goals "',
  "changing the way you want to buy and monetize your products",
  "monitor your startup with intelligent property cards",
  "accounts payable by sending clients data to complex more cash",
  "branded merchandise for your talents",
  "facebook messenger for web partners re - designed for teams",
  "monitor your startup with credit card rewards",
  "hawk - eye fantasy news",
  "a social network for the best places .",
  "a new way to discover new books",
  "build your own survival yourself",
  "the easiest way to clean and pay for cannabis / video . ( + invites ! )",
  "your personal assistant to help you organize your game",
  "meet new friends comfortably at your own branded fit",
  "your personal assistant for arranging appointments & marketing ( + invites ! )",
  '" a free , easy - to - use , authentic and trustful "',
  "revolutionary new way to target the world",
  "run your entire website design and sales",
  "achieve your weight with private feedback",
  "insider threat and productivity for customer service",
  "popup outdoor offices",
  "a mobile app that helps you to organise your digital wallet",
  "hang out your todo list and focus on the tasks",
  "hotel loyalty habits",
  "reinventing online fashion retail experience",
  "freshly - prepared healthy meals delivered in your inbox",
  "empower your team",
  "find and book yoga connection between your people .",
  "showcase your expertise to instagram on ipad",
  "tools to help you find and get in life",
  "interpret your world ' s social impact",
  "a visual messenger for content teams",
  "tracking and project management for your team",
  "build a beautiful website support for your business",
  "facebook messenger for web application",
  "mobile app that helps you to relive neck off internet",
  "markdown - flavored digital web app",
  "instantly provides a personal website for your data network",
  "empowering church leaders to enrich their youth ministry into google calendar",
  "all your plastic cards from one place",
  "enabling trustworthy due diligence exchange between investors and investees 3d printer",
  "train your brain to make your phone and get video messages",
  "an online community for animators",
  "business performance dashboards and price predictions",
  "superior box that keeps your cryptocurrency investments on every day",
  "large - file sharing for online forms",
  '" your team \' s collective knowledge , with a simple and agile ( invites ! ) "',
  "easy - to - use and powerful text messaging app",
  "discover and share whiskey with your friends",
  "transform your cluttered inbox into a potential of the spoken natural language",
  "daily deals for the lucky ( + give it",
  "sell your code at the perfect temperature until you show humanity",
  "turn your website traffic into a live video sites",
  "pay what you want to offer",
  "smart url shortener for production designers to help you grow their own projects",
  "test your startup idea before",
  "increase conversions with automated travel clients",
  "all - in - one business management platform for teams",
  "connecting the worlds greatest online and web",
  "spend less time worrying w / targeted emails",
  "discover new music artists",
  "connect with people who love to you",
  "free way to create and manage effective websites .",
  '" a free , high - resolution stock image site for kids ! "',
  "did your photos into lists with your friends",
  "the world ' s first ai - powered social media platform",
  "community for developers",
  "powerful marketing automation software for modern hr teams",
  "a better way to unique resources for developers",
  "a pinterest for your family and home",
  "simple and easy to use cryptocurrency portfolio",
  "hearing amplifiers that double as rechargeable bluetooth headphones",
  "manage your social media path in one place",
  "see how to build your website visitors",
  "a social network for your inner artist",
  "your personal assistant for arranging appointments & users",
  "single endpoint for high - risk situations",
  '" the easiest way to create a community - driven , free , real - time payments on the web . "',
  "democratizing the web process + sports teams",
  "create a chatbot that accepts you to your keyboard",
  "control your broken and location and time with beautiful interactive web application .",
  "super simple and powerful social media management platform",
  "the first app for trading experience",
  "bringing grocery list to the future of a button",
  "track your downloads & create a status page in a few clicks",
  "a local marketplace for fans and explorers who ' ve taken to sleep or whenever you love",
  '" a simple , private , non - intrusive for video and web "',
  "share your favorite moments and discover the best mobile devices",
  "the world ' s first user flow diagramming tool",
  '" find , share , and listen to your next big reviews "',
  '" a simple , photo sharing tool for startups "',
  "virtual investment bank app that teaches kids financial responsibility",
  "share your favorite music in the world ' s top investors",
  "invest your spare change",
  '" a simple , open application for creatives "',
  "monitor your startup with prettier",
  "an all - in - one learning platform for global ecommerce",
  '" a new way to discover , save and share content on your goals "',
  '" the easiest way to create a community of your car , kits . "',
  "ai - powered visual data platform for the mid market",
  '" simple , easy invoicing for your web projects "',
  "streamlines your recruitment workflow for your business",
  "anonymous voting platform",
  "password manager for designers .",
  "competitive data analysis for your apps",
  '" a free , intelligent , social network and organization for kids "',
  "helps you to optimize your team",
  "biggest content discovery for brand",
  "the easiest way to plan your wedding",
  '" the easiest way for creating a community , a new way to make new friends "',
  "the easiest way to create and share your personal website",
  "convert your website visitors  email into spreadsheet",
  "increase your revenue with private keys on market",
  "experience the world of banking",
  "helps you find groceries for the lowest price .",
  '" a new way to create , share and share your links "',
  "the fastest way to buy and consume digital photos with your friends .",
  '" a free , beautiful journalling app "',
  '" discover , connect and engage with the people you love "',
  '" a new way to discover , save and share content on the web . "',
  "share your favorite music online with the power of ai",
  "send direct and email sharing for free",
  "protect your credit card experience",
  "streamlines your recruitment workflow by your team",
  "provide the steam for your app",
  "discover the best locations to find the right person at the right time",
  "track your downloads & ecommerce in one place",
  '" learn how to match with your experts , forever "',
  '" the easiest way to create a custom mock - ups to share , sell , energy , and achieve goals "',
  "smart jewelry for emotional wellbeing",
  "virtual analyst tool for b2b",
  "your social media superhero",
  "a social network for sustainable fashion",
  "one - click debugging generator",
  "jamming with other people will be",
  "the easiest way to plan your wedding",
  "a tool to manage your hotel projects",
  "curated resources and tools for instant home",
  '" the easiest way to create a custom 3d printer , for the new way , track and care "',
  "1st ever calendar game for everyone",
  "fixing that helps you discover new things to a website",
  "improve your linkedin account knowledge",
  "a new way to read and share content on mobile",
  "get access to the best events to your schedule",
  "make money by selling for your meetings",
  "verified testimonials & convert any email address",
  "a mobile app that helps you to organise any music",
  "track your downloads from anywhere",
  '" a new way to discover , connect and communicate with your family "',
  "learning mandarin when you trust",
  '" create , read , and share stories on the web "',
  "automated email verification for tracking and clients",
  '" find the best new york for your design , nutrition , and beauty in real assets "',
  "share your favorite moments and get your favorite restaurants worldwide",
  "a new way to make more attentive to 10 %",
  "meet with the fun dating",
  "find your next tech and tips by following a local services",
  "a new way to crowdfund and share events around the world",
  '" discover , connect & engage with people make new friends "',
  "informs of the newest and most valuable parking fees",
  "a better way to find and share gift supplier",
  "change the way you share your city",
  "a social network for people who share and make a place",
  "an ai - driven analytics for mobile and personal website",
  "sell more products with pinterest",
  "leveraging your phone number into an adventure",
  "view your stats of coffee at the perfect temperature until you  ve tried . ( + invites ! )",
  "turn your smartphone into micro - file storage",
  "skip the small talk",
  '" the easiest way to surf your inspiration , anonymously and start chatting "',
  "be the freshest gal or # tcdisrupt",
  '" a new way to discover , connect content and investors "',
  '" the easiest way to move for anything , teams and designers to leads "',
  "a better way to get paid on your co - workers",
  "learn how to build promotions & campaigns",
  "simply your own saas application",
  "the easiest way to make a custom call online",
  "social - saving marketing tool",
  "convert your customers ' s full potential",
  "the easiest way to get things done",
  "follow up your email campaigns using a social network",
  "a collaborative social network for selfies with augmented reality",
  '" a simple , intuitive digital mapping platform for designers "',
  "create and share your online store",
  '" a free , real - time file sharing platform for designers are makers "',
  "connected dashcam with safety alerts & audio documentaries",
  "best profitability accounting software for agencies and small businesses",
  "listing management for your smartphone",
  "boost your hr software made easy",
  '" the easiest way to create a community around the world , a knight in the world . "',
  "turn your smartphone into a biking tool",
  "most unique way to look back - workers know",
  "the best way to separate and learn",
  '" create , read , and share stories of your scheduled links "',
  "an app that lets you discover the best of your convos",
  "share your favorite music with your favorite recipes . ( + invites ! )",
  "build your own survival an interactive online presence",
  "play your favorite products with your friends",
  "daily deals for the lucky ( + give and invite ! )",
  "stay up your tweets to your inbox",
  "multi - channel digital marketing platform",
  "increase customer engagement and voice calls",
  "set your status page in one place",
  "powering workplaces with talented and stock trading",
  "edit any email list just got a lot easier",
  "ai - powered visual content api",
  "the easiest way to discover the best events around you",
  "simply and share highlights",
  '" a simple , simple and powerful iot device "',
  "keep track of your travel history from your most trusted experience",
  "flying start a service that is actually want to use",
  '" a free , art of the web app "',
  "bank - level security for developers",
  "create a beautiful and secure website builder for your website",
  '" track your billable business in one place . we do it , all in the skin of crime fiction "',
  "build once run anywhere in your website",
  "design and tools for mobile apps",
  "you are the way you need to eat to you",
  "hotel management for your apps",
  "the easiest way to share your photos and locations",
  '" a free , high - resolution stock image site in a social network . "',
  "will manage your social marketing with a simple healthy",
  '" a free , elegant & social platform to create a live video game for kids "',
  "supercharge your team ' let ' s a audience and a human - like - it safe",
  "stay on top of your meetings and make striving and get more done .",
  "track your customers with personalized feedback and get honest proposals",
  "transform your cluttered inbox into a potential of your iphone app",
  "create a chatbot that allows you to the on - demand developer revenue for a personal touch",
  "a mobile app that helps you to organise your day to you .",
  "travis for unparalleled niche productivity app",
  "easily sell your social accounts with your friends .",
  "marketing automation for saas marketing teams",
  '" a new way to discover , connect and communicate with your contacts "',
  "grow your instagram by using ai",
  "documentation made easy",
  "secure microblogging tool for freelancers .",
  "a new way to message and engage with",
  "monitors your crohn ' s disease",
  '" the easiest way to create a community of a new way , for free "',
  "an ai - powered personal assistant for wordpress",
  "your personal assistant for arranging appointments & users",
  "siri for the rest of your life",
  "find the best seats . share things you love",
  "the easiest way to stay nourished for your event",
  "reinventing the way you have a quick and fun way",
  "beta and human website builder for wordpress",
  '" a free , encrypted browser - based beverages . "',
  '" a simple , accurate , and beautiful earth curvature calculator "',
  "create and share your own animated video content on the web",
  "access gyms . . . . . . . . . .",
  "lively trip planner",
  "the first app for the best naps of gaming",
  "convert any brand or a smart home security",
  "creates managed wordpress hosting",
  "hire the power of technology of your home",
  "one - click debugging of language",
  "makes your app to keep the best gameplay beautifully",
  "formal and social learning reimagined",
  "the easiest way to clean and organize your websites",
  "world ' s first digital babysitter",
  "maximizing tax savings for the web",
  "an interactive online video site generator",
  "a simple and easy way to create a custom keywords for your customer life",
  "get your app installed support buddy",
  '" explore and recommend app for writing , find jobs , and maintenance "',
  '" develop your website in seconds , and rent someone new friends "',
  "build a beautiful website in your browser",
  "automagically the good inventions written communication in the timeline",
  "buffer for transactional startups .",
  "provides data management for mobile & team",
  "we ' re making instagram by taking pictures",
  '" you can count on your point , change the way you are in the world "',
  "save money on the cloud",
  "connecting travelers with professional insights",
  "receive webhook requests in telegram",
  '" find , share and relive moments and learn "',
  "create a chatbot that keeps your data to explore the world",
  "merging mobile greeting cards in a click",
  '" the easiest way to create a community of a new way , for free "',
  '" the easiest way to keep track of business progress , collaborate , and read , and share "',
  '" the easiest way for creating a fun , truck , or suv "',
  "the fastest way to follow the world of things",
  "app for professionals to make smarter and their content",
  "the best way to start your friends",
  "podcasting meets snapchat generation",
  "taxi dispatch and fun and effective social network",
  "crypto portfolio manager",
  "stop living paycheck by sending emails",
  "notification center for busy developers",
  "drop - in - - one customer communication platform",
  "a platform for structured trading guide",
  "find the best places around you",
  "features and sales pipeline for agencies",
  "the smart device to discover and share events",
  '" create , read and share your favorite pieces of your favorite podcasts "',
  "challenge yourself a subscription crm to feature - based live chat in slack",
  "discover and share whiskey with your friends",
  "turn your smartphone into a biking tool",
  "create a chatbot that vanishes the stress - simple websites",
  '" the easiest way to create identity kits , whether they are you love "',
  "automate your social media follow up with a team",
  "10 additional intelligence ( early )",
  "an api for printing and shipping directly on hard",
  "enabling trustworthy due diligence out your tools and community with a points for games",
  "website specifications done right",
  "app for remembering names names",
  '" plan , track & analyse your competitors \' email campaigns "',
  "a new way to discover and share gift talks",
  "conversion calculator",
  "create your own online school for your business card",
  "follow - up your phone number",
  "start selling and create your own videos",
  "an online marketplace for type i diabetics to increase conversions",
  "private gratitude - end day to boost your productivity",
  "get a call - to - date with business",
  "get your app installed activity with your friends",
  "a smart keypad lock for the mac of the web",
  '" share , discover and relive moments and interesting people in the place "',
  "all your plastic cards are in the cloud",
  '" a simple , native content player for crafting and and developers management "',
  "find your next tech products in the world",
  '" a free , beautiful journalling app "',
  "digital mobile forms",
  "digital marketing suite",
  '" share , discover , take timestamped notes on your phone "',
  "eliminating machine learning",
  "social media marketing platform that helps businesses to build amazing 3d models and beyond",
  "let us your purchases and get hired with the right time",
  "30 - day fantasy sports",
  "easily track and share your travel routes",
  "connect with people who live on - demand services",
  '" find , share simple , and shared for your team "',
  "no - search selling text messages",
  '" a free , collaborative tool for the tragically apathetic "',
  "explore the world through web stories",
  "the best way to wait for your online portfolio",
  "ai - powered bicycle maintenance system",
  "tracks analytics for your customer experience",
  "your personal assistant for creative .",
  '" keep track of small businesses , even when you don \' t "',
  "all - in - one customer communication tool",
  "legal intelligence for web - forms",
  "create a chatbot that helps you to relive old conference talks on site",
  "protects your privacy",
  '" a free , private live chat app a personal browser , with a simple gameplay "',
  '" the easiest way to create a community for your way , store and share "',
  "world ' s first live chat for your workplace in a web apps",
  "quick and easy nps scores api for your favourite sites",
  "new social media marketing tools",
  "team collaboration and platform for tech companies",
  "the best way to discover new things to your friends",
  '" the most intuitive , yet powerful way for creatives "',
  "makes it easy to - do list of contractors - get rewarded",
  "startup metrics for your startup",
  "it ' s a smart remote control tool",
  "set up to your resolutions by adding clickable links",
  "employee attendance and leave approval collaboration platform",
  '" the easiest way to create a quick and local , real time for today \' s best "',
  "stop wasting time recreating bugs on - the - go .",
  "simplify your world ' s social impact on the go",
  "discover and share whats social activities",
  "an interactive online video game board for the mid of a game of the home",
  "an ai - powered assistant for e - commerce",
  "the best way to hide your day",
  "the easiest way to search for unsplash photos with your mac",
  "customize & track your videos in one place",
  "simple & elegant & modular ui kit / awesome git repository",
  "interesting people who want to know",
  "business card scanner",
  "your daily fix of single - day",
  "improve your drawing account and keep the best specialty photos",
  '" a simple , real - time file sharing platform for designers "',
  '" a new way to discover , save and share content on your connections "',
  "simplifies the connection between apps and better stores",
  "a simple way to organize your projects",
  '" discover , share and listen to your contacts in the world "',
  '" enjoy and prioritize your biggest marketing , using / monthly seconds "',
  "first motivational task manager",
  '" a free , scalable tracker for developers and domains "',
  "a new way to share and share content / audios on your static",
  "connect with people through playing mobile games",
  "search engine for instagram dishes from all over international media",
  "a new way to experience your day",
  "crypto portfolio manager",
  "safely and receive bitcoins together .",
  "interact with your friends ( + invites ! )",
  "a simple and easy - to - use audit management system",
  "smart url shortener for awesome sales",
  "be the news anchor",
  "a social network for events",
  '" a free , cloud - based pos device "',
  "your personal assistant to help you organize your friends",
  "free open source api for websites",
  "earn up to 20 % back - free articles delivered to without all the sweat .",
  "manage your pantry inventory wisely .",
  "create a chatbot that rewards ' s health and less than 20 min a click",
  "share and discover great content on the web",
  '" the easiest way to manage your business has been writing " one stop influencer " " " "',
  "create and share your own animated gif",
  "get a real - time feedback from your ios - office",
  "ready - to - talk to your team without coding",
  "go to create your personal website using machine learning",
  "a smart home locker engine",
  "your personal assistant for arranging appointments",
  "transforms any tv into live video stories",
  "live chat with your mobile workforce",
  "temporary music for your favorite products",
  "the easiest way to get things done",
  '" a new way to discover , save & share content on your favorite things "',
  "find the best local deals on the web",
  '" a new way to discover , save and share content on the web . "',
  '" search , compare , and purchase tech products from your browser "',
  '" the easiest way to create a community connectivity on any app , or on - app "',
  "emotionally your own movie revenue app",
  "test your startup idea into real time to the ultimate email",
  "1 - click conversions and delivered to your inbox",
  "surveys for competitive gamers",
  "sharing platform for ui professionals",
  "making math learning with people who hate to learning",
  "helping android developers to help each other to guests the news",
  "forex and international money transfers with students",
  "wordpress speed optimization for $ 250 / month",
  '" a free , private way to learn new friends "',
  "turn your website traffic into a beautiful custom instant messaging app",
  "heavenly simple way to create interactive video tutorials with no - code",
  "fully customizable video sites",
  '" discover , share and listen to your dream job "',
  "share and discover great content on the web page",
  "create a beautiful and tools to explore and headlines on your hard - get paid on a blog",
  "modern intimacy app for all the web",
  "storify meets tumblr",
  "meet people with friends and buy",
  '" find , share , and listen to podcasts with your friends "',
  "personal finance software",
  "community where you can play with a swipe of your startup",
  "your personal assistant for arranging appointments",
  "a social network for high school industry - investment features",
  '" a free , secure & secure , online platform for kids "',
  "your personal assistant for arranging appointments & users",
  "nap your website in under 5 seconds .",
  "a curated collection of crafted goods & designs",
  "share your favorite moments and get the things done right",
  "email app that helps you to capture and engage conference and feel money",
  '" a simple , beautiful journalling app "',
  "write a screenplay the same way",
  "decentralized social network for $ 15 / mo",
  "share and discover great products with your friends",
  "photo - sharing gamified",
  "convert any brand or audience online",
  "free and easy to use cryptocurrency portfolio",
  '" a free , yet poweful for people mysql "',
  "simplicity of the newest curated articles and services",
  "the easiest way to send photos among friends",
  "get more done with your friends",
  "see the whole picture super a better way you care about",
  "a new way to communicate with your friends and organize your friends & want",
  "connecting advertisers with the world",
  "publish & share your amazing adventures",
  "automated morale and engagement platform for modern teams",
  "a real - time social network for people with friends .",
  "bet on your phone calls with your smartphone",
  '" find , organize , and share your configurations in seconds "',
  "connecting the worlds greatest instagram stories",
  "share your favorite music with the world ' s top investors",
  "3 minutes to your leads for your phone",
  "cyber security for your business",
  "a marketplace for the self - improvement and mobile - friendly",
  '" a new way to discover , connect and communicate with your favorite things "',
  "peace of mind for outlook users take care about your family",
  "notification center for your business",
  "streamline your startup with your favorite username on the market intelligence",
  '" a platform for agents to connect , connect and work drinks , and win more "',
  "digitize your favourite songs by embedding a few lines of code",
  "readworthy books for amazon businesses",
  '" an online examination , to - do list app "',
  "automatically create your own website online",
  "boost your motivation",
  "organize your world with renting a social network",
  '" build , rig , and animate your entire sales "',
  "tinder for the makers",
  "reinventing the way you share and grow",
  "stop wasting time and leverage for charity",
  "create and share your own animated gif",
  "single question the world .",
  "helps you find groceries in 10 seconds",
  '" create , deploy and share stories of your life "',
  "showcase your photos with the world",
  "simplest and fastest way to learn to find the world",
  "design collaboration tool for quickbooks",
  "the easiest way to create and share sustainable solutions .",
  "formal and social learning reimagined",
  "email marketing for the next billion deskless workers",
  '" a new way to create , manage , and share content on your twitter "',
  "a new way to crowdfund and share events",
  "activity with your friends and make it ' s on - demand done",
  "online marketplace for legal business",
  "make better decisions .",
  "interact with your friends using song lyrics",
  "helping international travellers to buy and sell their teams",
  "height adjustable smart investment trading",
  "instantly shareable sales and marketing analytics for your website",
  "digital diary / marketing",
  "app to optimize your products with your friends  s full price",
  "personal finance personlized",
  "anticipate so you get friends to eat and even when you eat like you",
  "a social network for coders",
  "give you can get the right for your team",
  "the first social laughing network",
  "reinventing the way you never want to be",
  "a social network for change the cultures",
  '" create , read and share your favorite pieces of your favorite podcasts "',
  "job hunting made easy",
  "tell the world of the world with a place",
  "the best way to manage your projects",
  "an intelligent assistant for personal finances",
  '" a new way to discover , connect & communicate with your competitors "',
  '" a new way for your team , scheduling and organization "',
  "wink the steam for the web",
  "summarized annual reports without a no - code source",
  "a simple and easy way to respond to similar mouse in a fun word .",
  '" a simple , low - touch program for creatives "',
  "simple and easy to use cryptocurrency portfolio",
  "upload your video in your website",
  "mock - ups with character privacy",
  "boost your website visitors is a smart assistant",
  "book accommodation & hotels in the most out of a place",
  "marketplace for prebuilt chatfuel and fitness through mobile api",
  "new social media marketing sharing app",
  "better social media marketing tool",
  "a new way to find friends and get awesome products on your home",
  '" a free , beautiful journalling app "',
  '" a simple , high - resolution stock image site for apple "',
  "turn your website traffic into a complete ticketing system",
  "the easiest way to learn to track your career",
  '" the easiest way to create a community of a new way to 10x via video playlists "',
  "a social network for musicians who are nutty about",
  "music discovery for the business",
  "contacts of recently & play your employees ' s cross - platform",
  "search engine for independent teams",
  "full - circle productivity tool for slack teams",
  "iconic headphones inspired by 100 + parameters",
  '" free , instant , and actionable analytics for stripe "',
  "get apis in your audience",
  "the most advanced analytics",
  '" a new way to discover , connect and communicate with the right people "',
  "freelance music discovery",
  '" create , distribute wordpress , and animate your entire "',
  '" get feedback from your friends , starting with your ipad "',
  "public fast and easy hosting  a better product",
  '" a simple , scalable backend for your business "',
  "share your favorite moments in the cloud",
  "dynamic face - to - one - one dashboard",
  "a simple and easy task management tool for global event",
  '" all your finances via facebook messenger for slack , sms "',
  "inspire and teach the world through video stories",
  "get a percentage of smart home for ios",
  "use your phone number",
  "turn your smartphone into a smart bike",
  "music discovery for sysadmins",
  "a new way to explore and share events",
  "glue the superstar in you",
  "making the moon accessible",
  "accounting software for small business & product",
  '" find , share and listen to your favorite coffee table "',
  "turns your facebook page into an unofficial coworking space",
  "home for your favorite search",
  "an automated webinar generator that lets you bring the most interesting community",
  "post your email list with referrals",
  "tap into the social media platform",
  '" discover , connect & engage with people "',
  "salesforce up to your employees ' s full potential",
  "beta test management for group and clients",
  "most creative and physical art",
  "purchased & bagged meal ingredients ready after deals hack their business professionals",
  "intelligent incident management for your app",
  "keep track of your favourite things in the world",
  '" a new way to discover , connect and communicate with your contacts "',
  "powerful and easy to use cryptocurrency portfolio",
  "the best way to your team",
  "planning engine for your ideas",
  "instantly resize your images faster with a few clicks",
  "prepare your instagram followers by sending customers",
  "free time tracking for your business",
  "allow your customers to your grandmom ' s audience on facebook messenger",
  "design and portfolio management in slack",
  "amazon for icos",
  "add a release notes and ratings for any anonymous",
  '" a new way to discover , save and share content on the web "',
  "online sporty entertainment and ios app for businesses",
  "the ultimate tool for teams",
  "only the best freelance talent",
  '" a new way to discover , connect and communicate with your writing "',
  "single endpoint for high - risk situations",
  "intelligent crm for complex businesses",
  '" easily keep track of your spending , learn from both them "',
  "discover the best networking around the world",
  "a fun way to increase your traffic",
  "contextual your body is really matter",
  "teach the world ' s best learning opportunities",
  "the easiest way to plan your wedding",
  "share and discover great content in your area",
  "use your phone number out and organize your voice",
  "the easiest way to anywhere on the things you love",
  "it ' s what ' s data to life .",
  "tell the world with productive experiences .",
  '" the easiest way to discover , onboard letters and services in tech companies "',
  "get the full of online courses in one place",
  "your smart home entertainment",
  "your personal assistant for a better",
  "help others to understand great content",
  "a new way to listen to do your site",
  '" a free , non - intrusive for more innovative "',
  "smart artificial intelligence powered songwriting assistant",
  "latest pictures from the most trusted market",
  "visualised microservice monitoring",
  "your personal assistant for the workplace",
  "schedule your instagram story to the middle east .",
  "a simple and easy solution to create your custom database",
  "the online dating app for business",
  '" the easiest way to discover , onboard & engage with brands and services "',
  "read and share your personal details safely and photos",
  "connect with people through mobile games",
  "record and share your music in the world",
  '" a new way to discover , connect and communicate with your html wallet "',
  "keep track of your dog ' s latest art and books",
  "actionable insights means your existing customers",
  '" a new way to discover , connect and communicate with the best gifts and lifestyle . "',
  '" the easiest way to create a community and engage , app or app for roommates "',
  "free transactional email marketing campaign management",
  "daily standups through video and messaging",
  '" save , organize and share your favorite pieces of your favorite songs "',
  "take control of your tasks and get connected recommendations",
  "smart url shortener for awesome sales pipeline",
  "combining project management for groups simple",
  "unleashing the true potential of your usb - c macbook",
  "turn your website traffic into easy to - do list",
  "team stress - free online payments in slack",
  "referring the best place to join the new friends and share",
  "providing the steam for your social media posts",
  "applicant tracking system for freelance freelancers",
  '" build , rig , and animate your entire data "',
  "an app that lets you discover the best places you want to",
  "video and image api in 30 seconds",
  "putting the fun & empower your team",
  "form eco - friendly habits easier than ever",
  "30 - day fantasy deals",
  "analyze and leverage your job search",
  '" a free , managed , social network for neighbourhoods "',
  "push changes of updates online",
  "discover the best locations strategies to your favorite instagram stories",
  "documents online with a mix of a glove",
  "the trusted platform for airbnb hosts to provide devices",
  "a one - stop hangover prevention",
  "automagically the good times or a place to share files into your faster with a few clicks",
  "open source platform to create backend - to - code process",
  "it ' s a new frontier ( stealth )",
  "make the homepage of online orders",
  "transforms plain text into goal with a minimum viable project",
  '" the easiest way to create a community for new things , perfect stories and embrace adventures "',
  "plan your wedding",
  '" the easiest way to create a community , feature or app idea for business "',
  "schedule your website visitors from any source in seconds",
  "in new 10 second food and habits by an invite ! )",
  "achieve your weight with 50 from your social style",
  "an automated social media platform for recreation boating",
  "p2p social network for gamers",
  "daily email list consent management",
  "real - time collaboration platform for facebook and next generation",
  "create and share your own animated video content on the go",
  '" a new way to discover , save and share content on the web "',
  "motivational task manager",
  "tools for user ' s lifecycle",
  "discover the best vertical storytellers and their past stories",
  "the online store for iphone with the world",
  "chat with your smart home",
  "the best way to become more attentive to be",
  "a mobile app that keeps your dreams and sellers to the world accept",
  "messaging platform for designers to their favorite users ' t have to list",
  "cloud - based itsm done .",
  "simple & elegant wordpress hosting for designers and development",
  "a better way to trade cryptocurrency",
  "capture & record any music online",
  "find the best dataviz resources and services",
  "50 - 90 % off airfare deals sent to the middle east .",
  "performance monitoring service",
  "mobile - first bank account designed for the blockchain experience",
  '" the easiest way to create a community website for developers , and publish "',
  "the easiest way to send messages to get together",
  '" the easiest way to create a live streaming app for groups , blogs and shares "',
  '" simple , easy and powerful iot management tool "',
  "legal intelligence platform",
  "a simple and easy way to create your content marketing campaigns",
  '" discover , connect and engage with people money at home "',
  '" the easiest way to create a community around the best , lost , and share web "',
  '" create , read , and share stories from apps and services "',
  "secure way to create beautiful interactive data visualizations",
  "a platform for structured cryptocurrency enthusiasts",
  "discover interesting people around you",
  "a better way to share and share gift ideas",
  "connecting advertisers with the community",
  "all - in - one collaborative tool for your business",
  "automated email signatures for designers",
  "photo sharing for startups",
  "unify the power of word of your usb",
  "boards & optimising e - commerce data",
  "german managed wordpress hosting and view",
  '" a free , universal profile that is a live chat for video conference "',
  "employee engagement platform for secure data",
  "explore and share your activities with friends",
  "a social network for your inner artist",
  "create and share your full of your data",
  '" get feedback from any website , subscribe to your own online just a pro "',
  "an automated social media influencer marketing",
  "fully automatet lead generation of 500 + design",
  "offset your carbon footprint in the cloud",
  "powerful yet easy - to - use audit management system for mobile and web",
  "stop wasting time recreating bugs on - the - go .",
  "your personal assistant to read and receive more done",
  "the world ' s first smart filter",
  '" a free , simple & beautiful way to improve networking "',
  "get a call - in - one website monitoring for developers",
  '" a free , easy - to - use , authentic and trustful "',
  "learn to trade your lifestyle",
  "the most advanced platform for managing events and leads",
  "we connect shippers and audible reviews on topics you love",
  "helps you find groceries for the lowest price",
  "free landing page generator",
  "intelligent e - commerce tool for slack",
  '" create , read , and share stories , and share your life - directly on slack "',
  "a tool for the best places around the world",
  "schedule your website visitors into easy to implement bitcoin alerts",
  '" a beautiful , real - time file sharing for the pro . "',
  "smart workouts for your pebble watch",
  "one - click chatbots that works for creatives",
  "artificial intelligence to predict and receive your employees easier",
  "manage your website speed",
  "planning and discover new products from all around who ' ' s on your phone",
  "share your favorite music products with your friends",
  "get your app installed enterprise with z - wave - enabled crypto trading game",
  "creating a clearer feedback tool for your website",
  '" an online platform to build , publish and download "',
  "give you a whole new perspective in blogging is doing and your organization",
  '" a new way to discover , share and relive your moments in the world "',
  "keep track of your distributed team",
  "ai - powered bicycle maintenance",
  "features and share your own branded page",
  '" a mobile app to gratify customers , day , & marketers "',
  "the easiest way to keep track of contacts in your city",
  '" a new way to discover , connect and communicate with your contacts "',
  '" a simple , elegant approach to managing wordpress themes "',
  "weekly student discounts by offering your social media",
  "ace the reading sections of the sat & team",
  "discover and share activities you ' re passionate about you",
  '" discover , share and listen to your content on your phone "',
  "create engaging contests & surveys for your brand and apps",
  "business performance management for your web phone",
  "change the way you hate to send and post on the go !",
  "one - click debugging built on the planet",
  '" a free , private , non - intrusive platform for your apps "',
  '" build , rig , and animate your single resume "',
  '" a simple , private , non - intrusive for your web connections . "',
  '" discover , connect and connect with people \' s new songs "',
  '" a new way to create , manage and share your content better . "',
  "performance monitoring down to gain data and other open source code",
  "an url shortener for challenges and designs .",
  "your personal assistant for arranging appointments",
  "meet people with friends are in the world",
  '" a free , high - resolution stock restaurant , virtual information at any music "',
  "meet people with friends is doing in the same",
  "a mobile app that works with your users in video and games .",
  "community on steroids",
  "tell the world of hidden what you need a chat",
  "the most powerful nutrition app ever created",
  "sports scores api for customer feedback",
  '" a new way to discover , connect and communicate with your contacts "',
  "custom frame your social media",
  "making craigslist safer and how to - do list",
  "collaboration app that keeps your daily style at games",
  "the first social laughing network",
  "better social media marketing platform",
  "next generation business resources to help you find encrypt your trip",
  "open source platform to optimize your credit card",
  "the world ' s 1st smart fitness t view .",
  '" find the best rooftop , the world , and on - page ! "',
  "find your next tech job or internship abroad",
  "your company ' s data everywhere",
  '" improve sleep , switch and manage your reputation "',
  '" find , share & discover the best deals "',
  "connecting fans and get started without writing a home",
  "have a skill ? self - hosted digital music discovery",
  "get a real - time restaurant feedback on ipad .",
  "create and share your money in the world often",
  '" chat with anyone , anywhere "',
  '" your team \' s collective knowledge , everywhere "',
  "networked virtual workspaces for iphone",
  "groups simple and easy - to - use personal expertise",
  "an automated social media client for everyone",
  "always pick the best content you share and teams on the same destination",
  "the first social laughing network",
  "pre - order upcoming vc reviews",
  "collaboration to help your business",
  "free invoice generator",
  "optimize your credit card with your phone",
  "focus on the important stuff",
  "have a skill ? make an online store for everyone",
  "maintainable & physical leads for your startup",
  "an online marketplace for small business teams",
  '" easily keep track of your spending , contacts and make money . "',
  "quickly deploy & scale containerized services",
  '" a free , macbook for design and tv shows "',
  '" a new way to discover , save and share content on - the world "',
  "hearing amplifiers that double as rechargeable bluetooth headphones",
  "intelligent routing for your application",
  "headless cms for your customer ' s lifecycle",
  "inspiring order to communications happen",
  "privacy policy generator",
  "a mobile app that works with your friends ' s ongoing",
  "password manager for designers",
  "create a beautiful and secure company meetings on your website",
  "powerful crm for mailchimp customer service",
  "all of your best flatshare",
  '" a free , real - time way to manage servers and transform your job "',
  "get your app installed smart idea using a social media app",
  "build your own survival referral marketing",
  "leverage your investment in cryptos and and easy",
  "making getting together . accomplish",
  "gathers all your content always up with one app",
  "unblock webservices from your funds playing social media",
  "analyze and leverage your favorite things",
  "changing the way of today  s best content",
  "talk to your tastes & preferences with crowdsourced text message",
  "the future of cloud computing",
  "takes care of your writing time",
  "makes it easy to track and engage with your team",
  "collect and organize your gifs with ease",
  "customer feedback management software for modern hr teams",
  "a mobile app that helps you to organise plans with your friends ' s projects .",
  "reduce android studio build times more customers",
  "get to know your friends ( + invites ! )",
  "earn up to 20 % off airfare deals from a screen",
  "discover new music and events",
  '" track , bill , and manage your projects "',
  "an ai - powered chatbots",
  "keep track of your dog ' s latest social networks",
  "customizable locator with a powerful website for your needs",
  "your personal website concierge report",
  "peer - to - peer rental marketplace for your website",
  "a new way to make yourself and consume your style",
  "talk to your tastes & preferences with crowdsourced reviews",
  "rent out what you need to do",
  "product validation software that makes it powerfully fast 5 second money",
  "create and share your design life",
  "turn your website traffic into a complete ticketing system",
  "a social network for stock investors",
  "assign chores to make your ideas",
  "free time tracking software for marketing teams",
  "siri for your next tech",
  "protect your company passwords securely with a simple drag - and - smartest camera",
  "iphone case management software",
  "50 + free website statistics for real time",
  "what you need to remember important things",
  "find your next tech and videos with a resume",
  "a new way to get honest youtube videos better",
  "a rank tracking and human - powered website sales",
  "smart way to manage software and sales teams",
  "education made easy",
  "a personalized news feed for developers",
  "lets you cycle to buy your instagram followers automatically",
  "crowdsourced catalog to make savings for your friends",
  "a simple and easy way to create your to manage projects",
  "a smarter way to manage your projects",
  "the most powerful workout tracker",
  "comprehensive wireframe kit for bootstrap for your children .",
  "a simple and easy way to respond to similar crypto emails",
  "the official platform for the best things you love",
  "unique way to create value to mobile applications without writing",
  "automate your social media  one - click assistant",
  "all - in - one saas platform for a mac",
  "add a checkout to any website",
  "the easiest way to new and exiting online courses in the cloud storage",
  "get notified when your extra space",
  "it ' s everything you need to run your first to - share your phone",
  "nest for hot water",
  "the best way to learn piano",
  "members only compliance software to help you spend",
  '" a new way to discover , connect and communicate with your life . "',
  "verified contact details for children",
  "the most advanced smartlamp ever created",
  "collect and organize your music",
  '" a free , open , user - driven review platform for apple \' s best product "',
  '" a simple , accurate , and beautiful earth curvature calculator "',
  '" a free , high - resolution stock image site for kids "',
  "feel while you like never before you need in your budget",
  "the easiest way to grow your software development",
  "find the best places to do things you love",
  "select your instagram moments in the cloud",
  "a new way to interact with your friends .",
  '" the easiest way to create , manage websites and files "',
  "remote control of your software deployments for your web ' s projects",
  "puts the best events \x03your friends and family easier",
  "share your favorite moments in your shoes and compare in the world ' s first fun .",
  "fast and easy way to share and document !",
  "tracks your startup funding in a few clicks",
  "find the best online communities in the world",
  "reclaim your idle dollar idea  million dollar ready - to - text message",
  '" a new way to discover , save and share content on the web . "',
  "automatic time tracking for cryptocurrency",
  "the first app that makes it to the fun to create your photos and share and plan things",
  "custom integrations to any web page",
  "securely the best freelance deals for your phone",
  "get notified when your favorite portfolios so you don ' t have a picture",
  "we help you pick and manage your team content",
  "online scratch map on the fly",
  "automatically share your contact work",
  "manage and collaborate on top of your meetings on your inbox",
  "learn how to build a minimum viable product or application",
  "the easiest way to get things done",
  '" simple , yet easy - to - use web hosting "',
  "the smart way to find creative people around the world",
  "team collaboration tool for multiple rental",
  "increase conversions with painless accounts and machine learning",
  '" the most intuitive , yet powerful way to help people "',
  "turns your facebook page into audio stories",
  "get help from experienced software developers",
  "a mobile app that helps you to organise your friendly meetup",
  '" search , compare and free websites in slack "',
  "jobs between your app easy",
  "smartest way to manage your crypto portfolio",
  "offers your brand to pay on the go for your favorite podcasts",
  "simplified approach to bug manager for small businesses",
  "knowledge base management",
  "rethink home cooking",
  '" a new way to create a custom shop for your app icon , truck , or suv "',
  "a social network for high school industry - makers",
  "find the best online life in the world",
  "light up to your website for everyone",
  "intelligent apple search for customer",
  "index your inspiration and screenshots",
  "innovative social shopping for automotive aftermarket products",
  "zapp the stress out of your hotelstay",
  "free email marketing for businesses",
  '" a free , native content player for business model , messengers and achievements "',
  "find the best seats to tutorials on the things you love",
  "personalized growth for passionate people",
  '" a free , solar coins for developers to measure employee engagement "',
  "websites that doesn ' t suck",
  "unlimited rank tracking for agencies and podcasters",
  '" a simple , low - touch program for business "',
  "seafarer locator software for facebook and marketing",
  '" a new way to discover , connect and communicate with your night now . "',
  "online hrm software for cyclists",
  '" a free , location - based social platform to create a better way to learn "',
  "connect with the power of influence",
  "order fulfillment & shipping online courses",
  "visualize your customers to concentrate and beat distraction",
  "create and share your best routes to explore itineraries",
  "the most powerful popup builder for your business .",
  "hosted continuous integration for all the web",
  "the smartest way to enjoy and distribute classical",
  "local seo keyword research w / predictive analytics",
  "a social network for teams",
  "post your email list in a few clicks .",
  '" a free , intuitive way to improve and cards and are innovative games "',
  "make better decisions .",
  "images on instagram by organising your goals",
  "a new way to make meetings and distribute your video",
  "live streaming built for makers",
  "self - service communication between two slack",
  '" a new way to discover , save and share content on apps "',
  "automate your social media and team",
  "saas analytics for agile and product management",
  "redefining company  s data to launch your phone",
  "get your app installed articles from any source app",
  "planning and analysis of your finances",
  "the world ' s 1st smart fitness t - shirt with navigation",
  "app that lets airbnb guests book over the planet to get the right time for you",
  '" a free , low - touch program as a virtual record collection "',
  "visualize your customers with like - minded people",
  "changing the way to get the best networking with the right motivation",
  "the easiest way to make your friends while watching",
  "control your broken and sales process with a comprehensive time",
  '" read , track and analyze data with beautiful technical , use the web "',
  "a simple way to create and share your ideas and products",
  "a social network for the best places .",
  "create a beautiful and convenient messaging app for better",
  "changing the way to play for london photos",
  "uses artificial intelligence to drive users using achievement",
  "helping readers and writers learning again",
  "the easiest way to build your app that sell on your website",
  "simple and easy to use cryptocurrency portfolio",
  "seekers in just 5 taps",
  "smart water monitoring service",
  '" a free , native , social network for creatives "',
  "groups simple and easy way to share your mobile applications",
  "request and share your customer ' s life",
  "expert webcam cover sticker",
  "just another from your favorite founders",
  "a social network for high school industry",
  "an html5 design - and code - powered video game for blockchain",
  '" the easiest way to create , manage and share your presence . "',
  "style at the ones you love",
  "one - click debugging for your sw",
  "turns your facebook page before building your users take view",
  "the smart way to sell your email",
  "private gratitude - ready api for wordpress",
  "let your friends pick not their own money",
  "smart workouts based on your mac",
  "the best way to create a status page room",
  "keep track of your trusted currency projects right in real time",
  "the first app for the best naps of food & entertainment",
  "a mobile app that helps employers hiring users on google analytics",
  "multi - level security for small businesses",
  "team communication between landlords & tenants",
  '" your personal assistant , like a pro with a simple and fun ! "',
  "sms management for agencies and freelancers",
  "a free way to manage your static site",
  "get a percentage of the best deals for personal and home",
  "summarized annual reports without writing a single tap",
  "local seo keyword training",
  "find the best seats to explore the best product decisions",
  "a shopping for the fast and native apps .",
  "issue tracking and project management",
  "helping marketers build an artificial intelligence to a human - like a line of code",
  "automates your team ' s with ai client",
  "live chat with your friends",
  '" manage your assets , heirs , inheritance , funeral and discuss ideas "',
  "next generation universal job board",
  "organize and share your ideas",
  "a / b testing for developers and designers .",
  "automatically share your favorite moments and engage with others",
  "send and receive shipments with your friends .",
  "the most advanced smartlamp ever created",
  "rent out noise in new tab to see the music discovery",
  "rapidly build your website for every webshop",
  "@ sponsorship for consumer and good posts",
  "team communication between landlords and tenants",
  "the easiest way to turn your team ' s best restaurants",
  "your personal assistant to your pocket",
  "create your own online school for your business - card"
];

const generateBtn = document.getElementById("generate-btn");
const pitchText = document.getElementById("pitch-text");
const max = output.length;

const shareTwitter = document.getElementById("share-twitter");
const shareFacebook = document.getElementById("share-facebook");
const linkTwitter = document.getElementById("link-twitter");
const linkFacebook = document.getElementById("link-facebook");

generateBtn.addEventListener("click", e => {
  let randomNum = Math.floor(Math.random() * Math.floor(max));
  pitchText.innerText = output[randomNum];
});

shareTwitter.addEventListener("click", e => {
  let newHref = "https://twitter.com/intent/tweet?text=" + pitchText.innerText + '%20🦄%20https://pitchgen.co' + '%20%40akinhwan';
  linkTwitter.href = newHref;

  // add links, hashtags, images
});
